-- Migration: Add AI Trading Tables
-- Created: 2025-11-22
-- Description: Adds tables for AI-powered news trading functionality

-- AI Trade Context Table
-- Stores global market context generated by AI
CREATE TABLE IF NOT EXISTS ai_trade_context (
  id SERIAL PRIMARY KEY,
  context_data JSONB NOT NULL,
  summary TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  expires_at TIMESTAMP,
  model_version VARCHAR(100),
  token_count INTEGER
);

CREATE INDEX IF NOT EXISTS idx_ai_context_expires ON ai_trade_context(expires_at);
CREATE INDEX IF NOT EXISTS idx_ai_context_created ON ai_trade_context(created_at DESC);

-- AI News Articles Table
-- Stores news articles processed by the AI trading system
CREATE TABLE IF NOT EXISTS ai_news_articles (
  id SERIAL PRIMARY KEY,
  headline TEXT NOT NULL,
  summary TEXT,
  author TEXT,
  content TEXT,
  symbols TEXT[],
  source TEXT,
  url TEXT,
  published_at TIMESTAMP,
  received_at TIMESTAMP DEFAULT NOW(),
  processed BOOLEAN DEFAULT FALSE,
  sentiment VARCHAR(50),
  impact_score DECIMAL(5,2)
);

CREATE INDEX IF NOT EXISTS idx_news_symbols ON ai_news_articles USING GIN(symbols);
CREATE INDEX IF NOT EXISTS idx_news_processed ON ai_news_articles(processed);
CREATE INDEX IF NOT EXISTS idx_news_published ON ai_news_articles(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_news_received ON ai_news_articles(received_at DESC);

-- AI Trade Reasoning Table
-- Stores AI's reasoning and decision-making process for each trade
CREATE TABLE IF NOT EXISTS ai_trade_reasoning (
  id SERIAL PRIMARY KEY,
  trade_id VARCHAR(255),
  news_article_id INTEGER REFERENCES ai_news_articles(id) ON DELETE SET NULL,
  reasoning TEXT NOT NULL,
  sentiment VARCHAR(50),
  confidence_score DECIMAL(5,2),
  context_used JSONB,
  symbols_analyzed TEXT[],
  decision VARCHAR(20),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_reasoning_trade ON ai_trade_reasoning(trade_id);
CREATE INDEX IF NOT EXISTS idx_reasoning_article ON ai_trade_reasoning(news_article_id);
CREATE INDEX IF NOT EXISTS idx_reasoning_created ON ai_trade_reasoning(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_reasoning_decision ON ai_trade_reasoning(decision);

-- Update bots table to support AI-enabled trading
ALTER TABLE bots
  ADD COLUMN IF NOT EXISTS ai_enabled BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS ai_model VARCHAR(100),
  ADD COLUMN IF NOT EXISTS ai_config JSONB;

CREATE INDEX IF NOT EXISTS idx_bots_ai_enabled ON bots(ai_enabled) WHERE ai_enabled = TRUE;

-- Update bot_trades table to link with news and AI reasoning
ALTER TABLE bot_trades
  ADD COLUMN IF NOT EXISTS news_article_id INTEGER REFERENCES ai_news_articles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ai_reasoning_id INTEGER REFERENCES ai_trade_reasoning(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS ai_confidence DECIMAL(5,2);

CREATE INDEX IF NOT EXISTS idx_bot_trades_news_article ON bot_trades(news_article_id);
CREATE INDEX IF NOT EXISTS idx_bot_trades_ai_reasoning ON bot_trades(ai_reasoning_id);

-- AI News Stream Status Table
-- Tracks the status of news stream connections
CREATE TABLE IF NOT EXISTS ai_news_stream_status (
  id SERIAL PRIMARY KEY,
  stream_name VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL,
  connected_at TIMESTAMP,
  disconnected_at TIMESTAMP,
  error_message TEXT,
  articles_processed INTEGER DEFAULT 0,
  last_article_at TIMESTAMP,
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_stream_status ON ai_news_stream_status(stream_name, status);

-- Comments for documentation
COMMENT ON TABLE ai_trade_context IS 'Stores global market context generated by AI for trading decisions';
COMMENT ON TABLE ai_news_articles IS 'Stores news articles from Alpaca news stream';
COMMENT ON TABLE ai_trade_reasoning IS 'Stores AI reasoning and decision-making process for trades';
COMMENT ON TABLE ai_news_stream_status IS 'Tracks news stream connection status and metrics';

COMMENT ON COLUMN bots.ai_enabled IS 'Whether this bot uses AI for trading decisions';
COMMENT ON COLUMN bots.ai_model IS 'AI model used (e.g., gemini-2.0-flash-exp)';
COMMENT ON COLUMN bots.ai_config IS 'AI-specific configuration for this bot';

COMMENT ON COLUMN bot_trades.news_article_id IS 'News article that triggered this trade';
COMMENT ON COLUMN bot_trades.ai_reasoning_id IS 'AI reasoning for this trade decision';
COMMENT ON COLUMN bot_trades.ai_confidence IS 'AI confidence score for this trade (0-100)';
